name: kube-eks-cli
description: "Provide the kubectl command to make actions on your eks cluster."
author: 'Jonathan Henrique'
branding:
  icon: 'terminal'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'